set(GEOGRAPHICLIB_FOUND TRUE)
set(GeographicLib_INCLUDE_DIR /home/pashok/local/include/)
set(GeographicLib_LIBRARY /home/pashok/local/lib/libGeographic.so)
set(GeographicLib_LIBRARY_DIR /home/pashok/local/lib/)
#set(GeographicLib_INCLUDE_DIR C:/Users/Pavel/local/include/)
#set(GeographicLib_LIBRARY C:/Users/Pavel/local/lib/GeographicLib14.dll)
#set(GeographicLib_LIBRARY_DIR C:/Users/Pavel/local/lib/)
